const LOCAL_DRAFT_KEY = 'lhk_local_draft_v1';
const LOCAL_UI_KEY = 'lhk_ui_state_v1';
const TOKEN_KEY = 'lhk_token_v1';
const API_ENDPOINT = '/api/gas';

let deferredInstallPrompt = null;
let token = '';
let sessionUser = null;
let authNonce = 0;
let currentDays = [];
let sigPembuatB64 = '';
let sigAtasanB64 = '';
let atasanOptions = [];
let heartbeatTimer = null;

function escapeHtml(s){return String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function isStandaloneMode(){return window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true;}
function setInstallButtonVisible(show){const btn=document.getElementById('btnInstallPwa'); if(!btn) return; btn.classList.toggle('hidden', !show);}
function bumpAuthNonce(){authNonce++; return authNonce;}
function finishBoot(){document.body.classList.remove('booting');}
function toast(msg, ms=2200){const el=document.getElementById('toast'); if(!el){alert(msg||''); return;} el.textContent=msg||''; el.classList.remove('hidden'); clearTimeout(window.__toastT); window.__toastT=setTimeout(()=>el.classList.add('hidden'), ms);}
function setLoginStatus(msg){const el=document.getElementById('loginStatus'); if(el) el.textContent=msg||'';}
function setStatus(msg){const el=document.getElementById('status'); if(el) el.textContent=msg||'';}
function readFileAsB64(file, cb){const r=new FileReader(); r.onload=()=>{const s=String(r.result||''); const m=s.match(/^data:.+;base64,(.*)$/); cb(m?m[1]:'');}; r.onerror=()=>cb(''); r.readAsDataURL(file);}
function saveTokenLocal(t){try{ if(t) localStorage.setItem(TOKEN_KEY,t); else localStorage.removeItem(TOKEN_KEY);}catch(e){}}
function loadTokenLocal(){try{return localStorage.getItem(TOKEN_KEY)||'';}catch(e){return '';}}
function saveUiState(){try{localStorage.setItem(LOCAL_UI_KEY, JSON.stringify({token, who:sessionUser, savedAt:new Date().toISOString()}));}catch(e){}}

async function apiCall(api, payload={}){
  const res = await fetch(API_ENDPOINT, {
    method: 'POST',
    headers: {'Content-Type':'application/json'},
    body: JSON.stringify({api, token: token || '', payload})
  });
  if(!res.ok){ throw new Error('HTTP ' + res.status); }
  const json = await res.json();
  if(json && json.ok === false){ throw new Error(json.message || json.error || 'Request gagal'); }
  return json;
}
async function apiCallRetry(api, payload={}, retry=1){ let lastErr; for(let i=0;i<=retry;i++){ try{return await apiCall(api,payload);} catch(err){ lastErr=err; if(!navigator.onLine) break; await new Promise(r=>setTimeout(r,800*(i+1))); } } throw lastErr; }

function modalShow({title='Informasi', body='', actions=[]}){
  const m=document.getElementById('modal'), card=document.getElementById('modalCard');
  if(!m||!card){ alert(title + '\n\n' + String(body||'').replace(/<[^>]*>/g,'')); return; }
  document.getElementById('modalTitle').textContent=title;
  document.getElementById('modalBody').innerHTML=body;
  const act=document.getElementById('modalActions'); act.innerHTML='';
  actions.forEach(a=>{ const btn=document.createElement('button'); btn.type='button'; btn.textContent=a.label; btn.className=a.kind==='secondary'?'secondary':(a.kind==='danger'?'danger':''); btn.onclick=()=>{modalHide(); if(typeof a.onClick==='function') a.onClick();}; act.appendChild(btn); });
  if(!actions.length){ const btn=document.createElement('button'); btn.type='button'; btn.textContent='Tutup'; btn.className='secondary'; btn.onclick=modalHide; act.appendChild(btn); }
  m.classList.remove('hidden'); m.style.display='flex';
  document.getElementById('modalCloseBtn').onclick=modalHide;
  m.onclick=(ev)=>{if(ev.target===m) modalHide();};
  card.onclick=(ev)=>ev.stopPropagation();
}
function modalHide(){ const m=document.getElementById('modal'); if(!m) return; m.classList.add('hidden'); m.style.display='none'; m.onclick=null; const c=document.getElementById('modalCard'); if(c) c.onclick=null; const btn=document.getElementById('modalCloseBtn'); if(btn) btn.onclick=null; }

function showLogin(){ document.getElementById('loginView')?.classList.remove('hidden'); document.getElementById('appView')?.classList.add('hidden'); }
function showApp(){ document.getElementById('loginView')?.classList.add('hidden'); document.getElementById('appView')?.classList.remove('hidden'); setInstallButtonVisible(!isStandaloneMode()); }
function toggleSection(id){ document.getElementById(id)?.classList.toggle('open'); }
window.toggleSection = toggleSection;
function openSection(id){ document.getElementById(id)?.classList.add('open'); }
function closeSection(id){ document.getElementById(id)?.classList.remove('open'); }
function setupDefaultSections(){ openSection('secLhkForm'); closeSection('secLhkColors'); closeSection('secLhkDraft'); openSection('secLhkPreview'); openSection('secFilesList'); openSection('secUploadLhk'); closeSection('secChangePassword'); closeSection('secChangeEmail'); openSection('secAdminUpload'); closeSection('secAdminNotif'); closeSection('secAdminOnlineUsers'); closeSection('secAdminUsers'); closeSection('secAdminLogs'); }
function showTab(name){ ['lhk','files','pass','admin'].forEach(t=>{ document.getElementById('view'+t.charAt(0).toUpperCase()+t.slice(1))?.classList.add('hidden'); document.getElementById('tab'+t.charAt(0).toUpperCase()+t.slice(1))?.classList.remove('active');}); document.getElementById('view'+name.charAt(0).toUpperCase()+name.slice(1))?.classList.remove('hidden'); document.getElementById('tab'+name.charAt(0).toUpperCase()+name.slice(1))?.classList.add('active'); if(name==='files') refreshFiles(); if(name==='pass') refreshUploadFolders(); if(name==='admin'){ adminRefreshUploadRoot(); adminRefreshUploadFolders(); adminRefreshNotifications(); adminRefreshNotificationsQuick(); adminRefreshOnlineUsers(); adminLoadUsers(); adminRefreshLogs(); } }
function bindLoginEnterBehavior(){ const userEl=document.getElementById('loginUsername'), passEl=document.getElementById('loginPass'); userEl?.addEventListener('keydown',e=>{ if(e.key==='Enter'){ e.preventDefault(); passEl?.focus(); }}); passEl?.addEventListener('keydown',e=>{ if(e.key==='Enter'){ e.preventDefault(); doLogin(); }}); }
function updateNetworkBanner(){ const el=document.getElementById('netBanner'); if(!el) return; if(navigator.onLine){ el.textContent='Koneksi aktif'; el.classList.remove('hidden','offline'); el.classList.add('online'); clearTimeout(window.__netBannerTimer); window.__netBannerTimer=setTimeout(()=>el.classList.add('hidden'),1500);} else { clearTimeout(window.__netBannerTimer); el.textContent='Koneksi terputus. Draft lokal tetap aman.'; el.classList.remove('hidden','online'); el.classList.add('offline'); }}
function bindColorPreview(idInput, idPreview){ const input=document.getElementById(idInput), preview=document.getElementById(idPreview); if(!input||!preview) return; const sync=()=>preview.style.background=input.value||'#fff'; input.oninput=sync; sync(); }
function applySignatureModeUI(){ const mode=document.getElementById('signatureMode')?.value || 'text'; const row=document.getElementById('sigUploadRow'); if(!row) return; if(mode==='image') row.classList.remove('hidden'); else { row.classList.add('hidden'); sigPembuatB64=''; sigAtasanB64=''; const f1=document.getElementById('sigPembuatFile'), f2=document.getElementById('sigAtasanFile'); if(f1) f1.value=''; if(f2) f2.value=''; } saveLocalDraft(); }

function saveLocalDraft(){ try{ localStorage.setItem(LOCAL_DRAFT_KEY, JSON.stringify({savedAt:new Date().toISOString(), data:getFormData()})); }catch(e){} }
function loadLocalDraft(){ try{ const raw=localStorage.getItem(LOCAL_DRAFT_KEY); if(!raw) return false; const parsed=JSON.parse(raw||'{}'); if(!parsed?.data) return false; applyDraftToForm(parsed.data); return true; }catch(e){ return false; } }
function bindLocalAutosave(){ ['subBagian','jabatan','month','year','kota','holidays','fontOut','fontIn','jabatanAtasan','namaAtasan','colorHeader','colorDateCol','colorOffRow','enableOffHighlight','showSubHead','showKet','hideSaturday','hideSunday','signatureMode','pdfMode'].forEach(id=>{ const el=document.getElementById(id); if(!el) return; el.addEventListener('input', saveLocalDraft); el.addEventListener('change', saveLocalDraft); }); setInterval(()=>{ try{saveLocalDraft();}catch(e){} }, 5000); }
function resetCurrentDaysIfPeriodChanged(){ const month=Number(document.getElementById('month')?.value||0), year=Number(document.getElementById('year')?.value||0), prevMonth=Number(window.__lastPeriodMonth||0), prevYear=Number(window.__lastPeriodYear||0); if(month!==prevMonth || year!==prevYear){ currentDays=[]; window.__lastPeriodMonth=month; window.__lastPeriodYear=year; } }
function getFormData(){ return {nama:document.getElementById('nama')?.value||'', nip:document.getElementById('nip')?.value||'', subBagian:document.getElementById('subBagian')?.value||'', jabatan:document.getElementById('jabatan')?.value||'', jabatanPembuat:document.getElementById('jabatanPembuat')?.value||'', month:document.getElementById('month')?.value||'', year:document.getElementById('year')?.value||'', kota:document.getElementById('kota')?.value||'', holidays:document.getElementById('holidays')?.value||'', fontOut:document.getElementById('fontOut')?.value||'12', fontIn:document.getElementById('fontIn')?.value||'12', colorHeader:document.getElementById('colorHeader')?.value||'#dbeafe', colorDateCol:document.getElementById('colorDateCol')?.value||'#f3f4f6', colorOffRow:document.getElementById('colorOffRow')?.value||'#fef3c7', enableOffHighlight:document.getElementById('enableOffHighlight')?.value||'no', showSubHead:document.getElementById('showSubHead')?.value||'yes', showKet:document.getElementById('showKet')?.value||'yes', hideSaturday:document.getElementById('hideSaturday')?.value||'no', hideSunday:document.getElementById('hideSunday')?.value||'no', jabatanAtasan:document.getElementById('jabatanAtasan')?.value||'', namaAtasan:document.getElementById('namaAtasan')?.value||'', nipAtasan:document.getElementById('nipAtasan')?.value||'', sigPembuatB64, sigAtasanB64, exportMode:false, signatureMode:document.getElementById('signatureMode')?.value||'text', pdfMode:document.getElementById('pdfMode')?.value||'default', days:currentDays}; }
function applyDraftToForm(d){ const setVal=(id,val)=>{ const el=document.getElementById(id); if(el) el.value=val ?? '';}; ['subBagian','jabatan','jabatanPembuat','month','year','kota','holidays','fontOut','fontIn','jabatanAtasan','namaAtasan','nipAtasan','colorHeader','colorDateCol','colorOffRow','enableOffHighlight','showSubHead','showKet','hideSaturday','hideSunday','signatureMode','pdfMode'].forEach(id=>setVal(id,d[id]|| (id==='colorHeader' ? '#dbeafe' : id==='colorDateCol' ? '#f3f4f6' : id==='colorOffRow' ? '#fef3c7' : ''))); sigPembuatB64=d.sigPembuatB64||''; sigAtasanB64=d.sigAtasanB64||''; currentDays=Array.isArray(d.days)?d.days:[]; window.__lastPeriodMonth=Number(d.month||0); window.__lastPeriodYear=Number(d.year||0); bindColorPreview('colorHeader','previewColorHeader'); bindColorPreview('colorDateCol','previewColorDateCol'); bindColorPreview('colorOffRow','previewColorOffRow'); syncAtasanNip(); applySignatureModeUI(); updateHolidayPlaceholder(false); }

async function tryAutoLogin(){
  const t=loadTokenLocal();
  if(!t){ finishBoot(); showLogin(); if(loadLocalDraft()) toast('Draft lokal dipulihkan'); return; }
  try{ token=t; const res=await apiCall('getSession', {}); sessionUser=res.user||null; finishBoot(); afterLogin(true); }
  catch(err){ saveTokenLocal(''); token=''; finishBoot(); showLogin(); if(loadLocalDraft()) toast('Draft lokal dipulihkan'); }
}
async function doLogin(){ const username=(document.getElementById('loginUsername')?.value||'').trim(), pass=document.getElementById('loginPass')?.value||''; if(!username||!pass){ setLoginStatus('Isi username dan password terlebih dahulu.'); return; } setLoginStatus('Sedang login...'); try{ const res=await apiCallRetry('login',{username,password:pass},1); token=res.token||''; sessionUser=res.user||null; saveTokenLocal(token); saveUiState(); modalHide(); afterLogin(false); }catch(err){ setLoginStatus(err?.message||String(err)); } }
function doLogout(){ bumpAuthNonce(); const oldToken=token; stopHeartbeat(); if(window.__syncTimer){ clearInterval(window.__syncTimer); window.__syncTimer=null; } token=''; sessionUser=null; currentDays=[]; sigPembuatB64=''; sigAtasanB64=''; atasanOptions=[]; saveTokenLocal(''); try{localStorage.removeItem(LOCAL_UI_KEY);}catch(e){} try{document.getElementById('preview').srcdoc='';}catch(e){} setStatus(''); setLoginStatus(''); try{document.getElementById('loginUsername').value=''; document.getElementById('loginPass').value='';}catch(e){} showLogin(); showTab('lhk'); if(oldToken){ fetch(API_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api:'logout',token:oldToken,payload:{}})}).catch(()=>{}); } }
function startHeartbeat(){ stopHeartbeat(); if(!token) return; apiCall('heartbeat',{}).catch(()=>{}); heartbeatTimer=setInterval(()=>{ if(!token) return; apiCall('heartbeat',{}).catch(()=>{}); },60000); }
function stopHeartbeat(){ if(heartbeatTimer){ clearInterval(heartbeatTimer); heartbeatTimer=null; }}

async function afterLogin(isAuto){
  if(!sessionUser) return;
  showApp();
  const whoami=document.getElementById('whoami'); if(whoami) whoami.textContent=`${sessionUser.nama} (${sessionUser.nip}) - ${sessionUser.role}`;
  document.getElementById('nama').value=sessionUser.nama||''; document.getElementById('nip').value=sessionUser.nip||'';
  const isAdminLike=String(sessionUser.role||'').toLowerCase()==='admin';
  document.getElementById('tabAdmin')?.classList.toggle('hidden', !isAdminLike);
  document.getElementById('adminQuickRow')?.classList.toggle('hidden', !isAdminLike);
  const now=new Date(); document.getElementById('month').value=String(now.getMonth()+1); document.getElementById('year').value=String(now.getFullYear());
  const month=document.getElementById('month'), year=document.getElementById('year');
  if(window.__holidayPlaceholderHandler){ month?.removeEventListener('change', window.__holidayPlaceholderHandler); year?.removeEventListener('change', window.__holidayPlaceholderHandler); }
  window.__holidayPlaceholderHandler=()=>{ resetCurrentDaysIfPeriodChanged(); updateHolidayPlaceholder(false); };
  month?.addEventListener('change', window.__holidayPlaceholderHandler); year?.addEventListener('change', window.__holidayPlaceholderHandler);
  window.__lastPeriodMonth=Number(now.getMonth()+1); window.__lastPeriodYear=Number(now.getFullYear());
  const jab=document.getElementById('jabatan'), jp=document.getElementById('jabatanPembuat'); if(jp) jp.disabled=true;
  window.__mirrorJabatanPembuat=()=>{ if(jp) jp.value=(jab&&jab.value)?jab.value:''; };
  if(jab) jab.oninput=window.__mirrorJabatanPembuat;
  try{ const opt=await apiCallRetry('getOptions',{},1); fillSelect('subBagian', opt?.subBagian||[]); fillSelect('jabatanAtasan', opt?.kasubbag||[]); fillAtasanSelect(opt?.atasanList||[]); const namaAtasan=document.getElementById('namaAtasan'); if(namaAtasan) namaAtasan.onchange=syncAtasanNip; }catch(e){}
  try{ const res=await apiCallRetry('getMyPrefs',{},1); const p=res?.prefs||{}; ['subBagian','jabatan','kota','jabatanPembuat','jabatanAtasan','namaAtasan'].forEach(id=>{ const el=document.getElementById(id); if(el) el.value=p[id] || el.value || '';}); syncAtasanNip(); window.__mirrorJabatanPembuat?.(); }catch(e){}
  refreshDrafts(); refreshUploadFolders();
  const f1=document.getElementById('sigPembuatFile'), f2=document.getElementById('sigAtasanFile');
  if(f1) f1.onchange=()=>{ const file=f1.files&&f1.files[0]; if(!file){ sigPembuatB64=''; return; } readFileAsB64(file,b64=>{ sigPembuatB64=b64||''; if(sigPembuatB64) toast('Tanda tangan pembuat berhasil dimuat'); saveLocalDraft(); });};
  if(f2) f2.onchange=()=>{ const file=f2.files&&f2.files[0]; if(!file){ sigAtasanB64=''; return; } readFileAsB64(file,b64=>{ sigAtasanB64=b64||''; if(sigAtasanB64) toast('Tanda tangan atasan berhasil dimuat'); saveLocalDraft(); });};
  document.getElementById('signatureMode')?.addEventListener('change', applySignatureModeUI);
  bindColorPreview('colorHeader','previewColorHeader'); bindColorPreview('colorDateCol','previewColorDateCol'); bindColorPreview('colorOffRow','previewColorOffRow');
  applySignatureModeUI(); window.__mirrorJabatanPembuat?.(); setupDefaultSections(); startHeartbeat(); if(isAdminLike){ adminRefreshNotificationsQuick(); adminRefreshOnlineUsers(); } updateHolidayPlaceholder(false); if(!isAuto) toast('Login berhasil');
}

function fillSelect(id, arr){ const sel=document.getElementById(id); if(!sel) return; sel.innerHTML=''; (arr||[]).forEach(v=>{ const o=document.createElement('option'); o.value=v; o.textContent=v; sel.appendChild(o);}); }
function fillAtasanSelect(arr){ atasanOptions=Array.isArray(arr)?arr:[]; const sel=document.getElementById('namaAtasan'); if(!sel) return; sel.innerHTML=''; atasanOptions.forEach(x=>{ const o=document.createElement('option'); o.value=x.nama||''; o.textContent=x.nama||''; sel.appendChild(o);}); syncAtasanNip(); }
function syncAtasanNip(){ const sel=document.getElementById('namaAtasan'), nip=document.getElementById('nipAtasan'); if(!sel||!nip) return; const picked=atasanOptions.find(x=>String(x.nama||'')===String(sel.value||'')); nip.value=picked ? (picked.nip||'') : ''; }
async function updateHolidayPlaceholder(autoFill=false){ const month=document.getElementById('month')?.value||'', year=document.getElementById('year')?.value||'', holidaysEl=document.getElementById('holidays'); if(!holidaysEl||!token||!month||!year) return; try{ const res=await apiCall('getHolidayPlaceholderData',{month,year}); const placeholder=res?.placeholder||'', datesOnly=res?.datesOnly||''; holidaysEl.placeholder=placeholder?`Otomatis: ${placeholder}`:'Contoh: 1 10 17 atau 1,10,17 atau 2026-03-29'; if(autoFill && !String(holidaysEl.value||'').trim() && datesOnly) holidaysEl.value=datesOnly; }catch(e){ holidaysEl.placeholder='Contoh: 1 10 17 atau 1,10,17 atau 2026-03-29'; }}

async function generatePreview(){ resetCurrentDaysIfPeriodChanged(); setStatus('Membuat preview...'); saveLocalDraft(); const form=getFormData(); try{ const res=await apiCallRetry('renderPreviewHtml', form, 1); const html=res?.html||''; document.getElementById('preview').srcdoc=html; setStatus('Preview siap. Anda bisa menambah baris dan mengedit isi tabel langsung dari preview.'); setTimeout(()=>attachIframeSync(),300); }catch(err){ setStatus('Error: ' + (err?.message||err)); toast('Preview gagal. Draft lokal sudah disimpan.'); } }
function attachIframeSync(){ const iframe=document.getElementById('preview'); if(!iframe) return; let doc=null; try{ doc=iframe.contentDocument || iframe.contentWindow.document; }catch(e){ return; } if(!doc) return; syncRowsFromIframe(); doc.querySelectorAll('#tbl textarea').forEach(el=>el.addEventListener('input', ()=>syncRowsFromIframe())); if(window.__syncTimer) clearInterval(window.__syncTimer); window.__syncTimer=setInterval(syncRowsFromIframe,500); }
function syncRowsFromIframe(){ const iframe=document.getElementById('preview'); if(!iframe) return; let doc=null; try{ doc=iframe.contentDocument || iframe.contentWindow.document; }catch(e){ return; } if(!doc) return; const oldMap=new Map((Array.isArray(currentDays)?currentDays:[]).map(d=>[Number(d.day), {day:Number(d.day), activities:Array.isArray(d.activities)?d.activities.map(a=>({uraian:a?.uraian??'', output:a?.output??'', ket:a?.ket??''})):[]} ])); const rows=Array.from(doc.querySelectorAll('#tbl tbody tr[data-day][data-act]')); const visibleDays=new Set(); rows.forEach(tr=>{ const day=Number(tr.getAttribute('data-day')); if(Number.isFinite(day)) visibleDays.add(day); }); visibleDays.forEach(day=>oldMap.set(day, oldMap.get(day) || {day, activities:[]})); rows.forEach(tr=>{ const day=Number(tr.getAttribute('data-day')); const act=Number(tr.getAttribute('data-act')); if(!Number.isFinite(day)||!Number.isFinite(act)) return; const prevDay=Array.isArray(currentDays)?currentDays.find(d=>Number(d.day)===day):null; const prevAct=prevDay && Array.isArray(prevDay.activities) && prevDay.activities[act] ? prevDay.activities[act] : {uraian:'', output:'', ket:''}; const nextAct={uraian:prevAct?.uraian??'', output:prevAct?.output??'', ket:prevAct?.ket??''}; tr.querySelectorAll('textarea[data-field]').forEach(el=>{ const field=el.getAttribute('data-field'); if(field==='uraian'||field==='output'||field==='ket') nextAct[field]=el.value??'';}); if(!oldMap.has(day)) oldMap.set(day,{day,activities:[]}); oldMap.get(day).activities[act]=nextAct; }); const days=Array.from(oldMap.values()).sort((a,b)=>a.day-b.day); days.forEach(d=>{ d.activities=(d.activities||[]).filter(Boolean); if(!d.activities.length) d.activities=[{uraian:'', output:'', ket:''}]; }); currentDays=days; saveLocalDraft(); }
async function downloadExcel(){ resetCurrentDaysIfPeriodChanged(); saveLocalDraft(); setStatus('Membuat file Excel...'); try{ const res=await apiCallRetry('exportExcel', getFormData(), 1); const link=document.createElement('a'); link.href=`data:${res.mimeType};base64,${res.base64}`; link.download=res.fileName||'LHK.xlsx'; document.body.appendChild(link); link.click(); link.remove(); setStatus('Excel berhasil diunduh. File juga tersimpan di folder Anda: ' + (res.driveUrl || '')); }catch(err){ setStatus('Error: ' + (err?.message||err)); toast('Export Excel gagal. Coba lagi saat koneksi stabil.'); } }
async function downloadPdf(){ resetCurrentDaysIfPeriodChanged(); saveLocalDraft(); setStatus('Membuat PDF...'); const form=getFormData(); form.exportMode=true; form.pdfMode=document.getElementById('pdfMode')?.value || 'default'; try{ const res=await apiCallRetry('exportPdf', form, 1); const link=document.createElement('a'); link.href=`data:${res.mimeType};base64,${res.base64}`; link.download=res.fileName||'LHK.pdf'; document.body.appendChild(link); link.click(); link.remove(); setStatus('PDF berhasil diunduh. File juga tersimpan di folder Anda: ' + (res.driveUrl || '')); }catch(err){ setStatus('Error: ' + (err?.message||err)); toast('Export PDF gagal. Coba lagi saat koneksi stabil.'); } }
async function printPreview(){ resetCurrentDaysIfPeriodChanged(); setStatus('Menyiapkan tampilan print...'); const form=getFormData(); form.exportMode=true; try{ const res=await apiCallRetry('renderPreviewHtml', form, 1); const cleanHtml=res?.html||''; const w=window.open('', '_blank'); if(!w){ modalShow({title:'Print tidak tersedia', body:'Popup diblokir browser. Izinkan popup lalu coba lagi.'}); return; } w.document.open(); w.document.write(cleanHtml); w.document.close(); w.onload=()=>{w.focus(); w.print();}; setStatus('Tampilan print siap.'); }catch(err){ setStatus('Error: ' + (err?.message||err)); }}

async function refreshFiles(){ const status=document.getElementById('filesStatus'); if(status) status.textContent='Memuat daftar dokumen...'; try{ const res=await apiCall('listMyFiles',{}); const rows=Array.isArray(res)?res:(res?.list||[]); if(status) status.textContent=`Total file: ${rows.length}`; renderFilesTable(rows); }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
function renderFilesTable(list){ const box=document.getElementById('filesTable'); if(!box) return; if(!list?.length){ box.innerHTML='<div class="hint">Belum ada file yang tersimpan.</div>'; return; } let html='<table><tr><th>Nama File</th><th>Lokasi</th><th>Tanggal Dibuat</th><th>Akses</th></tr>'; list.forEach(f=>{ html += `<tr><td>${escapeHtml(f.name||'')}</td><td>${escapeHtml(f.location||'')}</td><td>${escapeHtml(f.created||'')}</td><td><a href="${f.url}" target="_blank">Buka</a></td></tr>`; }); html+='</table>'; box.innerHTML=html; }
async function openFolder(){ try{ const res=await apiCall('getMyFolderUrl',{}); const url=res?.url || res?.data || ''; if(url) window.open(url,'_blank'); }catch(e){ toast('Gagal membuka folder'); } }

async function refreshUploadFolders(){ const sel=document.getElementById('uploadFolder'), status=document.getElementById('uploadStatus'); if(!sel) return; sel.innerHTML=''; if(status) status.textContent='Memuat folder upload...'; try{ const res=await apiCall('listUploadFolders',{}); const rows=Array.isArray(res)?res:(res?.list||[]); if(!rows.length){ const o=document.createElement('option'); o.value=''; o.textContent='(Belum ada folder upload)'; sel.appendChild(o); if(status) status.textContent='Belum ada folder upload yang tersedia.'; return; } rows.forEach(x=>{ const o=document.createElement('option'); o.value=x.folderId; o.textContent=x.name||x.folderId; sel.appendChild(o); }); if(status) status.textContent='Pilih folder tujuan lalu unggah file PDF.'; }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
function uploadLhk(){ const folderId=document.getElementById('uploadFolder')?.value||'', fileEl=document.getElementById('uploadFile'), statusEl=document.getElementById('uploadStatus'); const file=fileEl && fileEl.files && fileEl.files[0]; if(!folderId){ if(statusEl) statusEl.textContent='Pilih folder tujuan terlebih dahulu.'; return; } if(!file){ if(statusEl) statusEl.textContent='Pilih file PDF terlebih dahulu.'; return; } if(!String(file.name||'').toLowerCase().endsWith('.pdf')){ if(statusEl) statusEl.textContent='File harus berformat PDF.'; return; } if(statusEl) statusEl.textContent='Mengunggah file...'; readFileAsB64(file, async b64=>{ if(!b64){ if(statusEl) statusEl.textContent='Gagal membaca file.'; return; } try{ const res=await apiCall('uploadLhkPdf',{folderId,fileName:file.name,base64:b64}); if(statusEl) statusEl.textContent='Upload berhasil: ' + (res.driveUrl||res.url||''); toast('Upload berhasil. Admin akan menerima notifikasi.'); try{fileEl.value='';}catch(e){} }catch(err){ if(statusEl) statusEl.textContent='Error: ' + (err?.message||err); modalShow({title:'Upload gagal', body:escapeHtml(err?.message||err)}); }}); }
async function changePassword(){ const oldP=document.getElementById('oldPass')?.value||'', newP=document.getElementById('newPass')?.value||'', status=document.getElementById('passStatus'); if(status) status.textContent='Menyimpan perubahan password...'; try{ await apiCall('changeMyPassword',{oldPassword:oldP,newPassword:newP}); if(status) status.textContent='Password berhasil diubah.'; document.getElementById('oldPass').value=''; document.getElementById('newPass').value=''; }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
async function changeEmail(){ const email=(document.getElementById('newEmail')?.value||'').trim(), status=document.getElementById('emailStatus'); if(status) status.textContent='Menyimpan perubahan email...'; try{ await apiCall('changeMyEmail',{newEmail:email}); if(status) status.textContent='Email berhasil diperbarui.'; document.getElementById('newEmail').value=''; toast('Email berhasil diperbarui'); }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); }}
function openRegister(){ modalShow({title:'Daftar Akun Baru', body:`<div class="hint" style="margin-bottom:10px">Akun yang didaftarkan dari sini otomatis memiliki role <b>user</b>.</div><label for="regNama">Nama</label><input id="regNama" placeholder="Masukkan nama lengkap"><label for="regUsername">Username</label><input id="regUsername" placeholder="Masukkan username login"><label for="regNip">NIP</label><input id="regNip" placeholder="Masukkan NIP"><label for="regEmail">Email</label><input id="regEmail" type="email" placeholder="user@domain.com"><label for="regPass">Password</label><input id="regPass" type="password" placeholder="Masukkan password">`, actions:[{label:'Batal',kind:'secondary'},{label:'Daftar', onClick: async ()=>{ const nama=(document.getElementById('regNama')?.value||'').trim(), username=(document.getElementById('regUsername')?.value||'').trim(), nip=(document.getElementById('regNip')?.value||'').trim(), email=(document.getElementById('regEmail')?.value||'').trim(), password=document.getElementById('regPass')?.value||''; toast('Mendaftarkan akun...'); try{ await apiCall('registerUser',{nama,username,nip,email,password}); toast('Pendaftaran berhasil. Silakan login.'); }catch(err){ modalShow({title:'Pendaftaran gagal', body:escapeHtml(err?.message||err)}); } }}]}); }
function openForgot(){ bumpAuthNonce(); toast('Membuka reset password...'); stopHeartbeat(); if(window.__syncTimer){ clearInterval(window.__syncTimer); window.__syncTimer=null; } token=''; sessionUser=null; currentDays=[]; saveTokenLocal(''); try{ localStorage.removeItem(LOCAL_UI_KEY); document.getElementById('loginPass').value=''; }catch(e){} showLogin(); modalShow({title:'Lupa Password', body:`<div class="hint" style="margin-bottom:10px">Masukkan NIP. Kode reset akan dikirim ke email yang terdaftar.</div><label for="fpNip">NIP</label><input id="fpNip" value=""><label for="fpCode">Kode Reset (6 digit)</label><input id="fpCode" placeholder="Contoh: 123456"><label for="fpNewPass">Password Baru</label><input id="fpNewPass" type="password"><div class="hint">Klik "Kirim Kode", lalu isi kode dan password baru, kemudian klik "Reset".</div>`, actions:[{label:'Tutup',kind:'secondary'},{label:'Kirim Kode',kind:'secondary',onClick: async ()=>{ const n=(document.getElementById('fpNip')?.value||'').trim(); toast('Mengirim kode reset...'); try{ const res=await apiCall('requestPasswordReset',{nip:n}); modalShow({title:'Informasi', body:escapeHtml(res?.message||'Jika terdaftar, kode akan dikirim.')}); }catch(err){ modalShow({title:'Gagal kirim kode', body:escapeHtml(err?.message||err)}); }}},{label:'Reset',onClick: async ()=>{ const n=(document.getElementById('fpNip')?.value||'').trim(), c=(document.getElementById('fpCode')?.value||'').trim(), p=document.getElementById('fpNewPass')?.value||''; toast('Mereset password...'); try{ await apiCall('resetPasswordWithCode',{nip:n,code:c,newPassword:p}); modalShow({title:'Sukses', body:'Password berhasil direset. Silakan login kembali.'}); }catch(err){ modalShow({title:'Gagal reset', body:escapeHtml(err?.message||err)}); }} } ]}); }

async function refreshDrafts(){ const sel=document.getElementById('draftSelect'); if(!sel) return; sel.innerHTML=''; try{ const res=await apiCall('listLhkDrafts',{}); const rows=Array.isArray(res)?res:(res?.list||[]); if(!rows.length){ const o=document.createElement('option'); o.value=''; o.textContent='(Belum ada draft)'; sel.appendChild(o); return; } rows.forEach(d=>{ const o=document.createElement('option'); o.value=d.fileId; o.textContent=`${d.name} — ${d.created}`; sel.appendChild(o); }); }catch(err){ modalShow({title:'Error', body:escapeHtml(err?.message||err)}); }}
async function saveDraft(){ toast('Menyimpan draft...'); try{ await apiCall('saveLhkDraft', getFormData()); toast('Draft berhasil disimpan'); refreshDrafts(); }catch(err){ modalShow({title:'Gagal simpan draft', body:escapeHtml(err?.message||err)}); }}
async function loadDraft(){ const id=document.getElementById('draftSelect')?.value||''; if(!id){ modalShow({title:'Informasi', body:'Pilih draft terlebih dahulu.'}); return; } toast('Memuat draft...'); try{ const res=await apiCall('loadLhkDraft',{fileId:id}); applyDraftToForm(res?.draft||{}); updateHolidayPlaceholder(false); toast('Draft berhasil dimuat'); }catch(err){ modalShow({title:'Gagal muat draft', body:escapeHtml(err?.message||err)}); }}
function deleteDraft(){ const id=document.getElementById('draftSelect')?.value||''; if(!id){ modalShow({title:'Informasi', body:'Pilih draft terlebih dahulu.'}); return; } modalShow({title:'Konfirmasi', body:'Hapus draft terpilih?', actions:[{label:'Batal',kind:'secondary'},{label:'Hapus',kind:'danger',onClick: async ()=>{ try{ await apiCall('deleteLhkDraft',{fileId:id}); toast('Draft berhasil dihapus'); refreshDrafts(); }catch(err){ modalShow({title:'Gagal hapus draft', body:escapeHtml(err?.message||err)}); } }}]}); }

async function adminRefreshNotificationsQuick(){ const box=document.getElementById('adminQuickInbox'); if(!box) return; box.innerHTML='Memuat...'; try{ const res=await apiCall('adminListNotifications',{}); const rows=res?.list||[]; if(!rows.length){ box.innerHTML='<span class="miniMuted">Belum ada notifikasi.</span>'; return; } box.innerHTML=rows.slice(0,3).map(x=>{ const isNew=String(x.isRead||'no')!=='yes'; return `<div style="margin-bottom:8px;"><span class="pill">${isNew?'Baru':'Dibaca'}</span><div style="margin-top:6px; font-weight:700;">${escapeHtml(x.title||'')}</div><div class="miniMuted">${escapeHtml(x.message||'')}</div></div>`; }).join(''); }catch(err){ box.innerHTML=`<span class="miniMuted">Error: ${escapeHtml(err?.message||err)}</span>`; }}
async function adminRefreshOnlineUsers(){ const status=document.getElementById('adminOnlineStatus'), box=document.getElementById('adminOnlineUsersTable'), sum=document.getElementById('adminOnlineSummary'); if(status) status.textContent='Memuat user online...'; if(sum) sum.innerHTML='Memuat...'; try{ const res=await apiCall('adminListOnlineUsers',{}); const rows=res?.list||[]; if(status) status.textContent=`Total user online: ${rows.length}`; if(sum){ sum.innerHTML=!rows.length?'<span class="miniMuted">Tidak ada user online.</span>':rows.slice(0,5).map(x=>`<div style="margin-bottom:8px;"><span class="pill">${escapeHtml(x.role||'')}</span><div style="margin-top:6px; font-weight:700;">${escapeHtml(x.nama||'')}</div><div class="miniMuted">${escapeHtml(x.nip||'')} • ${escapeHtml(x.lastSeen||'')}</div></div>`).join(''); } if(!box) return; if(!rows.length){ box.innerHTML='<div class="hint">Tidak ada user online.</div>'; return; } let html='<table><tr><th>NIP</th><th>Nama</th><th>Role</th><th>Last Seen</th></tr>'; rows.forEach(x=>{ html += `<tr><td>${escapeHtml(x.nip||'')}</td><td>${escapeHtml(x.nama||'')}</td><td>${escapeHtml(x.role||'')}</td><td>${escapeHtml(x.lastSeen||'')}</td></tr>`;}); html+='</table>'; box.innerHTML=html; }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); if(sum) sum.innerHTML=`<span class="miniMuted">Error: ${escapeHtml(err?.message||err)}</span>`; if(box) box.innerHTML=''; }}
async function adminRefreshNotifications(){ const status=document.getElementById('adminNotifStatus'); if(status) status.textContent='Memuat inbox admin...'; try{ const res=await apiCall('adminListNotifications',{}); const rows=res?.list||[]; if(status) status.textContent=`Total notifikasi: ${rows.length}`; renderAdminNotifications(rows); }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
function renderAdminNotifications(list){ const box=document.getElementById('adminNotifTable'); if(!box) return; if(!list?.length){ box.innerHTML='<div class="hint">Belum ada notifikasi masuk.</div>'; return; } let html='<table><tr><th>Waktu</th><th>Judul</th><th>Pesan</th><th>Status</th><th>Link</th><th>Aksi</th></tr>'; list.forEach(x=>{ html += `<tr><td>${escapeHtml(x.timestamp||'')}</td><td>${escapeHtml(x.title||'')}</td><td style="white-space:pre-wrap;">${escapeHtml(x.message||'')}</td><td>${escapeHtml((x.isRead||'no')==='yes'?'Dibaca':'Baru')}</td><td>${x.refId?`<a href="${x.refId}" target="_blank">Buka</a>`:'-'}</td><td><button type="button" class="secondary" style="margin-top:0; padding:6px 10px;" onclick="adminMarkNotificationRead('${String(x.notifId||'').replace(/'/g,"\\'")}')">Tandai Dibaca</button></td></tr>`; }); html+='</table>'; box.innerHTML=html; }
window.adminMarkNotificationRead = async function(notifId){ try{ await apiCall('adminMarkNotificationRead',{notifId}); toast('Notifikasi ditandai sudah dibaca'); adminRefreshNotifications(); adminRefreshNotificationsQuick(); }catch(err){ modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); }};
function adminClearNotifications(){ modalShow({title:'Konfirmasi', body:'Hapus semua notifikasi inbox admin?', actions:[{label:'Batal',kind:'secondary'},{label:'Hapus Semua',kind:'danger',onClick: async ()=>{ toast('Menghapus notifikasi...'); try{ await apiCall('adminClearNotifications',{}); toast('Inbox admin berhasil dibersihkan'); adminRefreshNotifications(); adminRefreshNotificationsQuick(); }catch(err){ modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); } }}]}); }
async function adminLoadUsers(){ const status=document.getElementById('adminStatus'); if(status) status.textContent='Memuat daftar pengguna...'; try{ const res=await apiCall('adminListUsers',{}); const rows=res?.list||[]; if(status) status.textContent=`Total user: ${rows.length}`; renderAdminUsers(rows); }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
function renderAdminUsers(list){ const box=document.getElementById('adminUsersTable'); if(!box) return; if(!list?.length){ box.innerHTML='<div class="hint">Belum ada data pengguna.</div>'; return; } let html='<table><tr><th>Username</th><th>NIP</th><th>Nama</th><th>Email</th><th>Role Saat Ini</th><th>Ubah Role</th><th>Aksi</th></tr>'; (list||[]).forEach(u=>{ const rawUsername=String(u.username||''), safeUsername=rawUsername.replace(/'/g,"\\'"), safeNip=String(u.nip||'').replace(/'/g,"\\'"), currentRole=String(u.role||'user').toLowerCase(), roleSelId='roleSel_'+rawUsername.replace(/[^a-zA-Z0-9_]/g,'_'); html += `<tr><td>${escapeHtml(rawUsername)}</td><td>${escapeHtml(u.nip||'')}</td><td>${escapeHtml(u.nama||'')}</td><td>${escapeHtml(u.email||'')}</td><td>${escapeHtml(currentRole)}</td><td><div style="display:flex; gap:8px; flex-wrap:wrap; align-items:center;"><select id="${roleSelId}" style="min-width:140px;"><option value="user" ${currentRole==='user'?'selected':''}>user</option><option value="sekretaris" ${currentRole==='sekretaris'?'selected':''}>sekretaris</option><option value="admin" ${currentRole==='admin'?'selected':''}>admin</option></select><button type="button" class="secondary" style="margin-top:0; padding:6px 10px;" onclick="adminChangeRoleFromList('${safeUsername}')">Simpan Role</button></div></td><td><button type="button" class="secondary" style="margin-top:0; padding:6px 10px;" onclick="adminResetPassFromList('${safeUsername}')">Reset</button><button type="button" class="danger" style="margin-top:0; padding:6px 10px;" onclick="adminDeleteUserFromList('${safeNip}')">Hapus</button></td></tr>`; }); html+='</table>'; box.innerHTML=html; }
window.adminChangeRoleFromList = async function(username){ const elId='roleSel_'+String(username||'').replace(/[^a-zA-Z0-9_]/g,'_'); const role=document.getElementById(elId)?.value||'user'; toast('Menyimpan role...'); try{ await apiCall('adminUpdateUserRole',{username,role}); toast('Role berhasil diperbarui'); adminLoadUsers(); }catch(err){ modalShow({title:'Gagal ubah role', body:escapeHtml(err?.message||err)}); }};
async function adminCreateUser(){ const nama=(document.getElementById('newUserNama')?.value||'').trim(), username=(document.getElementById('newUserUsername')?.value||'').trim(), nip=(document.getElementById('newUserNip')?.value||'').trim(), email=(document.getElementById('newUserEmail')?.value||'').trim(), pass=document.getElementById('newUserPass')?.value||'', role=document.getElementById('newUserRole')?.value||'user'; toast('Membuat user...'); try{ await apiCall('adminCreateUser',{nama,username,nip,email,password:pass,role}); toast('User berhasil dibuat'); ['newUserNama','newUserUsername','newUserNip','newUserEmail','newUserPass'].forEach(id=>document.getElementById(id).value=''); adminLoadUsers(); }catch(err){ modalShow({title:'Error', body:escapeHtml(err?.message||err)}); }}
window.adminResetPassFromList = function(username){ modalShow({title:'Reset Password', body:`<div class="hint">Reset password untuk username: <b>${escapeHtml(username)}</b></div><label for="rpNewPass">Password Baru</label><input id="rpNewPass" type="password" placeholder="Masukkan password baru">`, actions:[{label:'Batal',kind:'secondary'},{label:'Reset', onClick: async ()=>{ const pass=document.getElementById('rpNewPass')?.value||''; toast('Mereset password...'); try{ await apiCall('adminResetPassword',{username,newPassword:pass}); toast('Password berhasil direset'); adminLoadUsers(); }catch(err){ modalShow({title:'Error', body:escapeHtml(err?.message||err)}); } }}]}); };
window.adminDeleteUserFromList = function(nipOrUsername){ modalShow({title:'Konfirmasi', body:`Hapus user <b>${escapeHtml(nipOrUsername)}</b>?`, actions:[{label:'Batal',kind:'secondary'},{label:'Hapus',kind:'danger',onClick: async ()=>{ toast('Menghapus user...'); try{ await apiCall('adminDeleteUser',{nip:nipOrUsername}); toast('User berhasil dihapus'); adminLoadUsers(); }catch(err){ modalShow({title:'Error', body:escapeHtml(err?.message||err)}); } }}]}); };
async function adminRefreshUploadRoot(){ const hint=document.getElementById('uploadRootHint'); if(hint) hint.textContent='Memuat root folder...'; try{ const res=await apiCall('adminGetUploadRoot',{}); document.getElementById('uploadRootId').value=res?.folderId||''; if(hint) hint.innerHTML=res?.url ? `Root aktif: <a href="${res.url}" target="_blank">${res.url}</a>` : ''; }catch(err){ if(hint) hint.textContent='Error: ' + (err?.message||err); }}
async function adminSaveUploadRoot(){ const id=(document.getElementById('uploadRootId')?.value||'').trim(); if(!id){ toast('Isi Folder ID terlebih dahulu'); return; } toast('Menyimpan root folder...'); try{ await apiCall('adminSetUploadRootFolder',{urlOrId:id}); toast('Root folder berhasil disimpan'); adminRefreshUploadRoot(); adminRefreshUploadFolders(); refreshUploadFolders(); }catch(err){ modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); }}
async function adminCreateUploadFolder(){ const name=(document.getElementById('newUploadFolderName')?.value||'').trim(); if(!name){ toast('Isi nama folder terlebih dahulu'); return; } toast('Membuat folder...'); try{ await apiCall('adminCreateUploadFolder',{name}); toast('Folder upload berhasil dibuat'); document.getElementById('newUploadFolderName').value=''; adminRefreshUploadFolders(); refreshUploadFolders(); }catch(err){ modalShow({title:'Gagal buat folder', body:escapeHtml(err?.message||err)}); }}
async function adminRefreshUploadFolders(){ const status=document.getElementById('adminUploadStatus'); if(status) status.textContent='Memuat daftar folder upload...'; try{ const res=await apiCall('adminListUploadFolders',{}); const rows=res?.list||[]; if(status) status.textContent=`Total folder: ${rows.length}`; renderAdminUploadFolders(rows); refreshUploadFolders(); }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
function renderAdminUploadFolders(list){ const box=document.getElementById('adminUploadFoldersTable'); if(!box) return; if(!list?.length){ box.innerHTML='<div class="hint">Belum ada folder upload.</div>'; return; } let html='<table><tr><th>Nama Folder</th><th>Folder ID</th><th>Dibuat</th><th>Link</th><th>Aksi</th></tr>'; list.forEach(x=>{ html += `<tr><td>${escapeHtml(x.name||'')}</td><td>${escapeHtml(x.folderId||'')}</td><td>${escapeHtml(x.created||'')}</td><td><a href="${x.url}" target="_blank">Buka Folder</a></td><td><button type="button" class="danger" style="margin-top:0; padding:6px 10px;" onclick="adminDeleteUploadFolder('${String(x.folderId||'').replace(/'/g,"\\'")}')">Hapus</button></td></tr>`; }); html+='</table>'; box.innerHTML=html; }
window.adminDeleteUploadFolder = function(folderId){ modalShow({title:'Konfirmasi', body:`Folder upload ini akan dipindahkan ke Trash Google Drive.<br><br><b>${escapeHtml(folderId)}</b>`, actions:[{label:'Batal',kind:'secondary'},{label:'Hapus',kind:'danger',onClick: async ()=>{ toast('Menghapus folder...'); try{ await apiCall('adminDeleteUploadFolder',{folderId}); toast('Folder berhasil dihapus'); adminRefreshUploadFolders(); refreshUploadFolders(); }catch(err){ modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); } }}]}); };
async function adminRefreshLogs(){ const status=document.getElementById('adminLogsStatus'); if(status) status.textContent='Memuat log aktivitas...'; try{ const res=await apiCall('adminListLogs',{limit:500}); const rows=res?.list||[]; if(status) status.textContent=`Total log tampil: ${rows.length}`; renderAdminLogs(rows); }catch(err){ if(status) status.textContent='Error: ' + (err?.message||err); }}
function renderAdminLogs(list){ const box=document.getElementById('adminLogsTable'); if(!box) return; if(!list?.length){ box.innerHTML='<div class="hint">Belum ada log aktivitas.</div>'; return; } let html='<table><tr><th>Waktu</th><th>User</th><th>Role</th><th>Aksi</th><th>Detail</th><th>Hapus</th></tr>'; list.forEach(x=>{ html += `<tr><td>${escapeHtml(x.time||'')}</td><td>${escapeHtml((x.nama||'') + ' (' + (x.nip||'') + ')')}</td><td>${escapeHtml(x.role||'')}</td><td>${escapeHtml(x.action||'')}</td><td style="max-width:420px; white-space:pre-wrap;">${escapeHtml(x.detail||'')}</td><td><button type="button" class="danger" style="margin-top:0; padding:6px 10px;" onclick="adminDeleteLog(${Number(x.rowNum||0)})">Hapus</button></td></tr>`; }); html+='</table>'; box.innerHTML=html; }
window.adminDeleteLog = async function(logRowNum){ try{ await apiCall('adminDeleteLogs',{rowNums:[Number(logRowNum)]}); toast('Log berhasil dihapus'); adminRefreshLogs(); }catch(err){ modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); }};
function adminClearLogs(){ modalShow({title:'Konfirmasi', body:'Hapus semua log aktivitas?', actions:[{label:'Batal',kind:'secondary'},{label:'Hapus Semua',kind:'danger',onClick: async ()=>{ toast('Menghapus semua log...'); try{ await apiCall('adminClearLogs',{}); toast('Semua log berhasil dihapus'); adminRefreshLogs(); }catch(err){ modalShow({title:'Gagal', body:escapeHtml(err?.message||err)}); } }}]}); }

function registerPwa(){ if(isStandaloneMode()){ setInstallButtonVisible(false); return; } setInstallButtonVisible(true); if(!('serviceWorker' in navigator)) return; window.addEventListener('beforeinstallprompt', e=>{ e.preventDefault(); deferredInstallPrompt=e; setInstallButtonVisible(true); toast('Aplikasi siap di-install');}); window.addEventListener('appinstalled', ()=>{ deferredInstallPrompt=null; setInstallButtonVisible(false); toast('Aplikasi berhasil di-install');}); navigator.serviceWorker.register('/sw.js').catch(err=>console.warn('SW gagal:', err)); }
async function installPwa(){ if(isStandaloneMode()){ toast('Aplikasi sudah terpasang'); return; } if(deferredInstallPrompt){ try{ deferredInstallPrompt.prompt(); await deferredInstallPrompt.userChoice; }catch(e){ console.warn(e); } finally { deferredInstallPrompt=null; } return; } modalShow({title:'Pasang Aplikasi', body:`Install otomatis belum tersedia dari browser ini.<br><br><b>Di Chrome Android:</b><br>1. Tekan menu <b>⋮</b><br>2. Pilih <b>Tambahkan ke layar utama</b> atau <b>Install app</b><br>3. Lalu konfirmasi pemasangan`}); }

window.addEventListener('load', ()=>{
  setInstallButtonVisible(!isStandaloneMode());
  bindLoginEnterBehavior();
  window.addEventListener('online', updateNetworkBanner); window.addEventListener('offline', updateNetworkBanner);
  registerPwa(); updateNetworkBanner(); bindLocalAutosave();
  document.getElementById('loginView')?.classList.add('hidden'); document.getElementById('appView')?.classList.add('hidden');
  document.getElementById('btnInstallPwa')?.addEventListener('click', installPwa);
  document.getElementById('btnLogin')?.addEventListener('click', e=>{e.preventDefault(); doLogin();});
  document.getElementById('btnForgot')?.addEventListener('click', e=>{e.preventDefault(); openForgot();});
  document.getElementById('btnRegister')?.addEventListener('click', e=>{e.preventDefault(); openRegister();});
  document.getElementById('btnLogout')?.addEventListener('click', doLogout);
  document.querySelectorAll('.tab[data-tab]').forEach(el=>el.addEventListener('click', ()=>showTab(el.getAttribute('data-tab'))));
  document.getElementById('btnPreview')?.addEventListener('click', generatePreview);
  document.getElementById('btnDownload')?.addEventListener('click', downloadPdf);
  document.getElementById('btnDownloadExcel')?.addEventListener('click', downloadExcel);
  document.getElementById('btnPrint')?.addEventListener('click', printPreview);
  document.getElementById('btnPreviewMobile')?.addEventListener('click', generatePreview);
  document.getElementById('btnDownloadMobile')?.addEventListener('click', downloadPdf);
  document.getElementById('btnRefreshDrafts')?.addEventListener('click', refreshDrafts);
  document.getElementById('btnSaveDraft')?.addEventListener('click', saveDraft);
  document.getElementById('btnLoadDraft')?.addEventListener('click', loadDraft);
  document.getElementById('btnDeleteDraft')?.addEventListener('click', deleteDraft);
  document.getElementById('btnRefreshFiles')?.addEventListener('click', refreshFiles);
  document.getElementById('btnOpenFolder')?.addEventListener('click', openFolder);
  document.getElementById('btnUploadLhk')?.addEventListener('click', uploadLhk);
  document.getElementById('btnChangePass')?.addEventListener('click', changePassword);
  document.getElementById('btnChangeEmail')?.addEventListener('click', changeEmail);
  document.getElementById('btnAdminRefreshNotifications')?.addEventListener('click', ()=>{adminRefreshNotifications(); adminRefreshNotificationsQuick();});
  document.getElementById('btnAdminClearNotifications')?.addEventListener('click', adminClearNotifications);
  document.getElementById('btnAdminRefreshOnlineUsers')?.addEventListener('click', adminRefreshOnlineUsers);
  document.getElementById('btnAdminLoadUsers')?.addEventListener('click', adminLoadUsers);
  document.getElementById('btnAdminCreateUser')?.addEventListener('click', adminCreateUser);
  document.getElementById('btnAdminSaveUploadRoot')?.addEventListener('click', adminSaveUploadRoot);
  document.getElementById('btnAdminCreateUploadFolder')?.addEventListener('click', adminCreateUploadFolder);
  document.getElementById('btnAdminRefreshUploadFolders')?.addEventListener('click', adminRefreshUploadFolders);
  document.getElementById('btnAdminRefreshLogs')?.addEventListener('click', adminRefreshLogs);
  document.getElementById('btnAdminClearLogs')?.addEventListener('click', adminClearLogs);
  document.addEventListener('keydown', e=>{ if(e.key==='Escape'){ const m=document.getElementById('modal'); if(m && !m.classList.contains('hidden')) modalHide(); }});
  bindColorPreview('colorHeader','previewColorHeader'); bindColorPreview('colorDateCol','previewColorDateCol'); bindColorPreview('colorOffRow','previewColorOffRow');
  tryAutoLogin();
});
